package com.hycxkj.shop.bean;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.alibaba.fastjson.annotation.JSONField;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.hycxkj.common.annotation.PrimaryKey;
/**
 * 实体类对应的数据表为：  shop_comment
 * @author 陈少平
 * @date 2018-04-02 17:42:11
 */
@ApiModel(value ="ShopComment")
public class ShopComment implements Serializable {
    @PrimaryKey
    @ApiModelProperty(value = "唯一标识，插入的时候，自动生成")
    private Long shopCommentId;

    @ApiModelProperty(value = "商品ID")
    private Long shopItemId;

    @ApiModelProperty(value = "评论内容")
    private String comment;

    @ApiModelProperty(value = "评论时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date commentTime;

    @ApiModelProperty(value = "评分。满分10分，2分对应1颗星")
    private Byte ratingValue;

    @ApiModelProperty(value = "评论人姓名")
    private String ratingPersonName;

    @ApiModelProperty(value = "评论人头像")
    private String ratingPersonAvatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_comment
     */
    private static final long serialVersionUID = 1L;

    public Long getShopCommentId() {
        return shopCommentId;
    }

    public void setShopCommentId(Long shopCommentId) {
        this.shopCommentId = shopCommentId;
    }

    public Long getShopItemId() {
        return shopItemId;
    }

    public void setShopItemId(Long shopItemId) {
        this.shopItemId = shopItemId;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    public Date getCommentTime() {
        return commentTime;
    }

    public void setCommentTime(Date commentTime) {
        this.commentTime = commentTime;
    }

    public Byte getRatingValue() {
        return ratingValue;
    }

    public void setRatingValue(Byte ratingValue) {
        this.ratingValue = ratingValue;
    }

    public String getRatingPersonName() {
        return ratingPersonName;
    }

    public void setRatingPersonName(String ratingPersonName) {
        this.ratingPersonName = ratingPersonName;
    }

    public String getRatingPersonAvatar() {
        return ratingPersonAvatar;
    }

    public void setRatingPersonAvatar(String ratingPersonAvatar) {
        this.ratingPersonAvatar = ratingPersonAvatar;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", shopCommentId=").append(shopCommentId);
        sb.append(", shopItemId=").append(shopItemId);
        sb.append(", comment=").append(comment);
        sb.append(", commentTime=").append(commentTime);
        sb.append(", ratingValue=").append(ratingValue);
        sb.append(", ratingPersonName=").append(ratingPersonName);
        sb.append(", ratingPersonAvatar=").append(ratingPersonAvatar);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ShopComment other = (ShopComment) that;
        return (this.getShopCommentId() == null ? other.getShopCommentId() == null : this.getShopCommentId().equals(other.getShopCommentId()))
            && (this.getShopItemId() == null ? other.getShopItemId() == null : this.getShopItemId().equals(other.getShopItemId()))
            && (this.getComment() == null ? other.getComment() == null : this.getComment().equals(other.getComment()))
            && (this.getCommentTime() == null ? other.getCommentTime() == null : this.getCommentTime().equals(other.getCommentTime()))
            && (this.getRatingValue() == null ? other.getRatingValue() == null : this.getRatingValue().equals(other.getRatingValue()))
            && (this.getRatingPersonName() == null ? other.getRatingPersonName() == null : this.getRatingPersonName().equals(other.getRatingPersonName()))
            && (this.getRatingPersonAvatar() == null ? other.getRatingPersonAvatar() == null : this.getRatingPersonAvatar().equals(other.getRatingPersonAvatar()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getShopCommentId() == null) ? 0 : getShopCommentId().hashCode());
        result = prime * result + ((getShopItemId() == null) ? 0 : getShopItemId().hashCode());
        result = prime * result + ((getComment() == null) ? 0 : getComment().hashCode());
        result = prime * result + ((getCommentTime() == null) ? 0 : getCommentTime().hashCode());
        result = prime * result + ((getRatingValue() == null) ? 0 : getRatingValue().hashCode());
        result = prime * result + ((getRatingPersonName() == null) ? 0 : getRatingPersonName().hashCode());
        result = prime * result + ((getRatingPersonAvatar() == null) ? 0 : getRatingPersonAvatar().hashCode());
        return result;
    }
}