package com.hycxkj.shop.bean;

import java.io.Serializable;

import org.springframework.format.annotation.DateTimeFormat;
import com.alibaba.fastjson.annotation.JSONField;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.hycxkj.common.annotation.PrimaryKey;
/**
 * 实体类对应的数据表为：  shop_busi_item
 * @author 陈少平
 * @date 2018-05-06 21:30:16
 */
@ApiModel(value ="ShopBusiItem")
public class ShopBusiItem implements Serializable {
    @PrimaryKey
    @ApiModelProperty(value = "")
    private Long shopBusiItemId;

    @ApiModelProperty(value = "商家ID")
    private Long shopBusiId;

    @ApiModelProperty(value = "商品ID")
    private Long shopItemId;

    @ApiModelProperty(value = "邮费模板ID")
    private Long postageTemplateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_busi_item
     */
    private static final long serialVersionUID = 1L;

    public Long getShopBusiItemId() {
        return shopBusiItemId;
    }

    public void setShopBusiItemId(Long shopBusiItemId) {
        this.shopBusiItemId = shopBusiItemId;
    }

    public Long getShopBusiId() {
        return shopBusiId;
    }

    public void setShopBusiId(Long shopBusiId) {
        this.shopBusiId = shopBusiId;
    }

    public Long getShopItemId() {
        return shopItemId;
    }

    public void setShopItemId(Long shopItemId) {
        this.shopItemId = shopItemId;
    }

    public Long getPostageTemplateId() {
        return postageTemplateId;
    }

    public void setPostageTemplateId(Long postageTemplateId) {
        this.postageTemplateId = postageTemplateId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", shopBusiItemId=").append(shopBusiItemId);
        sb.append(", shopBusiId=").append(shopBusiId);
        sb.append(", shopItemId=").append(shopItemId);
        sb.append(", postageTemplateId=").append(postageTemplateId);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ShopBusiItem other = (ShopBusiItem) that;
        return (this.getShopBusiItemId() == null ? other.getShopBusiItemId() == null : this.getShopBusiItemId().equals(other.getShopBusiItemId()))
            && (this.getShopBusiId() == null ? other.getShopBusiId() == null : this.getShopBusiId().equals(other.getShopBusiId()))
            && (this.getShopItemId() == null ? other.getShopItemId() == null : this.getShopItemId().equals(other.getShopItemId()))
            && (this.getPostageTemplateId() == null ? other.getPostageTemplateId() == null : this.getPostageTemplateId().equals(other.getPostageTemplateId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getShopBusiItemId() == null) ? 0 : getShopBusiItemId().hashCode());
        result = prime * result + ((getShopBusiId() == null) ? 0 : getShopBusiId().hashCode());
        result = prime * result + ((getShopItemId() == null) ? 0 : getShopItemId().hashCode());
        result = prime * result + ((getPostageTemplateId() == null) ? 0 : getPostageTemplateId().hashCode());
        return result;
    }
}