package com.hycxkj.websocket.bean;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import com.alibaba.fastjson.annotation.JSONField;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.hycxkj.common.annotation.PrimaryKey;
/**
 * 实体类对应的数据表为：  ws_push
 * @author 陈少平
 * @date 2018-04-07 20:51:44
 */
@ApiModel(value ="Push")
public class Push implements Serializable {
    @PrimaryKey
    @ApiModelProperty(value = "唯一标识，自增主键")
    private Integer id;

    @ApiModelProperty(value = "推送内容")
    private String content;

    @ApiModelProperty(value = "推送时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date pushtime;

    @ApiModelProperty(value = "推送消息的人")
    private Integer pushid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ws_push
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    public Date getPushtime() {
        return pushtime;
    }

    public void setPushtime(Date pushtime) {
        this.pushtime = pushtime;
    }

    public Integer getPushid() {
        return pushid;
    }

    public void setPushid(Integer pushid) {
        this.pushid = pushid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", content=").append(content);
        sb.append(", pushtime=").append(pushtime);
        sb.append(", pushid=").append(pushid);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Push other = (Push) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getPushtime() == null ? other.getPushtime() == null : this.getPushtime().equals(other.getPushtime()))
            && (this.getPushid() == null ? other.getPushid() == null : this.getPushid().equals(other.getPushid()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getPushtime() == null) ? 0 : getPushtime().hashCode());
        result = prime * result + ((getPushid() == null) ? 0 : getPushid().hashCode());
        return result;
    }
}