package com.hycxkj.postage.bean;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class PostageTemplateExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table postage_postage_template
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table postage_postage_template
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table postage_postage_template
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table postage_postage_template
     */
    private static final long serialVersionUID = 1L;

    public PostageTemplateExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBusiIdIsNull() {
            addCriterion("busi_id is null");
            return (Criteria) this;
        }

        public Criteria andBusiIdIsNotNull() {
            addCriterion("busi_id is not null");
            return (Criteria) this;
        }

        public Criteria andBusiIdEqualTo(Long value) {
            addCriterion("busi_id =", value, "busiId");
            return (Criteria) this;
        }

        public Criteria andBusiIdNotEqualTo(Long value) {
            addCriterion("busi_id <>", value, "busiId");
            return (Criteria) this;
        }

        public Criteria andBusiIdGreaterThan(Long value) {
            addCriterion("busi_id >", value, "busiId");
            return (Criteria) this;
        }

        public Criteria andBusiIdGreaterThanOrEqualTo(Long value) {
            addCriterion("busi_id >=", value, "busiId");
            return (Criteria) this;
        }

        public Criteria andBusiIdLessThan(Long value) {
            addCriterion("busi_id <", value, "busiId");
            return (Criteria) this;
        }

        public Criteria andBusiIdLessThanOrEqualTo(Long value) {
            addCriterion("busi_id <=", value, "busiId");
            return (Criteria) this;
        }

        public Criteria andBusiIdIn(List<Long> values) {
            addCriterion("busi_id in", values, "busiId");
            return (Criteria) this;
        }

        public Criteria andBusiIdNotIn(List<Long> values) {
            addCriterion("busi_id not in", values, "busiId");
            return (Criteria) this;
        }

        public Criteria andBusiIdBetween(Long value1, Long value2) {
            addCriterion("busi_id between", value1, value2, "busiId");
            return (Criteria) this;
        }

        public Criteria andBusiIdNotBetween(Long value1, Long value2) {
            addCriterion("busi_id not between", value1, value2, "busiId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andAddrIsNull() {
            addCriterion("addr is null");
            return (Criteria) this;
        }

        public Criteria andAddrIsNotNull() {
            addCriterion("addr is not null");
            return (Criteria) this;
        }

        public Criteria andAddrEqualTo(String value) {
            addCriterion("addr =", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrNotEqualTo(String value) {
            addCriterion("addr <>", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrGreaterThan(String value) {
            addCriterion("addr >", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrGreaterThanOrEqualTo(String value) {
            addCriterion("addr >=", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrLessThan(String value) {
            addCriterion("addr <", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrLessThanOrEqualTo(String value) {
            addCriterion("addr <=", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrLike(String value) {
            addCriterion("addr like", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrNotLike(String value) {
            addCriterion("addr not like", value, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrIn(List<String> values) {
            addCriterion("addr in", values, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrNotIn(List<String> values) {
            addCriterion("addr not in", values, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrBetween(String value1, String value2) {
            addCriterion("addr between", value1, value2, "addr");
            return (Criteria) this;
        }

        public Criteria andAddrNotBetween(String value1, String value2) {
            addCriterion("addr not between", value1, value2, "addr");
            return (Criteria) this;
        }

        public Criteria andPackageMailIsNull() {
            addCriterion("package_mail is null");
            return (Criteria) this;
        }

        public Criteria andPackageMailIsNotNull() {
            addCriterion("package_mail is not null");
            return (Criteria) this;
        }

        public Criteria andPackageMailEqualTo(Boolean value) {
            addCriterion("package_mail =", value, "packageMail");
            return (Criteria) this;
        }

        public Criteria andPackageMailNotEqualTo(Boolean value) {
            addCriterion("package_mail <>", value, "packageMail");
            return (Criteria) this;
        }

        public Criteria andPackageMailGreaterThan(Boolean value) {
            addCriterion("package_mail >", value, "packageMail");
            return (Criteria) this;
        }

        public Criteria andPackageMailGreaterThanOrEqualTo(Boolean value) {
            addCriterion("package_mail >=", value, "packageMail");
            return (Criteria) this;
        }

        public Criteria andPackageMailLessThan(Boolean value) {
            addCriterion("package_mail <", value, "packageMail");
            return (Criteria) this;
        }

        public Criteria andPackageMailLessThanOrEqualTo(Boolean value) {
            addCriterion("package_mail <=", value, "packageMail");
            return (Criteria) this;
        }

        public Criteria andPackageMailIn(List<Boolean> values) {
            addCriterion("package_mail in", values, "packageMail");
            return (Criteria) this;
        }

        public Criteria andPackageMailNotIn(List<Boolean> values) {
            addCriterion("package_mail not in", values, "packageMail");
            return (Criteria) this;
        }

        public Criteria andPackageMailBetween(Boolean value1, Boolean value2) {
            addCriterion("package_mail between", value1, value2, "packageMail");
            return (Criteria) this;
        }

        public Criteria andPackageMailNotBetween(Boolean value1, Boolean value2) {
            addCriterion("package_mail not between", value1, value2, "packageMail");
            return (Criteria) this;
        }

        public Criteria andValuationmodelIsNull() {
            addCriterion("valuationModel is null");
            return (Criteria) this;
        }

        public Criteria andValuationmodelIsNotNull() {
            addCriterion("valuationModel is not null");
            return (Criteria) this;
        }

        public Criteria andValuationmodelEqualTo(Byte value) {
            addCriterion("valuationModel =", value, "valuationmodel");
            return (Criteria) this;
        }

        public Criteria andValuationmodelNotEqualTo(Byte value) {
            addCriterion("valuationModel <>", value, "valuationmodel");
            return (Criteria) this;
        }

        public Criteria andValuationmodelGreaterThan(Byte value) {
            addCriterion("valuationModel >", value, "valuationmodel");
            return (Criteria) this;
        }

        public Criteria andValuationmodelGreaterThanOrEqualTo(Byte value) {
            addCriterion("valuationModel >=", value, "valuationmodel");
            return (Criteria) this;
        }

        public Criteria andValuationmodelLessThan(Byte value) {
            addCriterion("valuationModel <", value, "valuationmodel");
            return (Criteria) this;
        }

        public Criteria andValuationmodelLessThanOrEqualTo(Byte value) {
            addCriterion("valuationModel <=", value, "valuationmodel");
            return (Criteria) this;
        }

        public Criteria andValuationmodelIn(List<Byte> values) {
            addCriterion("valuationModel in", values, "valuationmodel");
            return (Criteria) this;
        }

        public Criteria andValuationmodelNotIn(List<Byte> values) {
            addCriterion("valuationModel not in", values, "valuationmodel");
            return (Criteria) this;
        }

        public Criteria andValuationmodelBetween(Byte value1, Byte value2) {
            addCriterion("valuationModel between", value1, value2, "valuationmodel");
            return (Criteria) this;
        }

        public Criteria andValuationmodelNotBetween(Byte value1, Byte value2) {
            addCriterion("valuationModel not between", value1, value2, "valuationmodel");
            return (Criteria) this;
        }

        public Criteria andIsPackageConditionIsNull() {
            addCriterion("is_package_condition is null");
            return (Criteria) this;
        }

        public Criteria andIsPackageConditionIsNotNull() {
            addCriterion("is_package_condition is not null");
            return (Criteria) this;
        }

        public Criteria andIsPackageConditionEqualTo(Boolean value) {
            addCriterion("is_package_condition =", value, "isPackageCondition");
            return (Criteria) this;
        }

        public Criteria andIsPackageConditionNotEqualTo(Boolean value) {
            addCriterion("is_package_condition <>", value, "isPackageCondition");
            return (Criteria) this;
        }

        public Criteria andIsPackageConditionGreaterThan(Boolean value) {
            addCriterion("is_package_condition >", value, "isPackageCondition");
            return (Criteria) this;
        }

        public Criteria andIsPackageConditionGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_package_condition >=", value, "isPackageCondition");
            return (Criteria) this;
        }

        public Criteria andIsPackageConditionLessThan(Boolean value) {
            addCriterion("is_package_condition <", value, "isPackageCondition");
            return (Criteria) this;
        }

        public Criteria andIsPackageConditionLessThanOrEqualTo(Boolean value) {
            addCriterion("is_package_condition <=", value, "isPackageCondition");
            return (Criteria) this;
        }

        public Criteria andIsPackageConditionIn(List<Boolean> values) {
            addCriterion("is_package_condition in", values, "isPackageCondition");
            return (Criteria) this;
        }

        public Criteria andIsPackageConditionNotIn(List<Boolean> values) {
            addCriterion("is_package_condition not in", values, "isPackageCondition");
            return (Criteria) this;
        }

        public Criteria andIsPackageConditionBetween(Boolean value1, Boolean value2) {
            addCriterion("is_package_condition between", value1, value2, "isPackageCondition");
            return (Criteria) this;
        }

        public Criteria andIsPackageConditionNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_package_condition not between", value1, value2, "isPackageCondition");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table postage_postage_template
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}