package com.hycxkj.postage.bean;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class PostagePackageConditionExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table postage_package_condition
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table postage_package_condition
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table postage_package_condition
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table postage_package_condition
     */
    private static final long serialVersionUID = 1L;

    public PostagePackageConditionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPostageTemplateIdIsNull() {
            addCriterion("postage_template_id is null");
            return (Criteria) this;
        }

        public Criteria andPostageTemplateIdIsNotNull() {
            addCriterion("postage_template_id is not null");
            return (Criteria) this;
        }

        public Criteria andPostageTemplateIdEqualTo(Long value) {
            addCriterion("postage_template_id =", value, "postageTemplateId");
            return (Criteria) this;
        }

        public Criteria andPostageTemplateIdNotEqualTo(Long value) {
            addCriterion("postage_template_id <>", value, "postageTemplateId");
            return (Criteria) this;
        }

        public Criteria andPostageTemplateIdGreaterThan(Long value) {
            addCriterion("postage_template_id >", value, "postageTemplateId");
            return (Criteria) this;
        }

        public Criteria andPostageTemplateIdGreaterThanOrEqualTo(Long value) {
            addCriterion("postage_template_id >=", value, "postageTemplateId");
            return (Criteria) this;
        }

        public Criteria andPostageTemplateIdLessThan(Long value) {
            addCriterion("postage_template_id <", value, "postageTemplateId");
            return (Criteria) this;
        }

        public Criteria andPostageTemplateIdLessThanOrEqualTo(Long value) {
            addCriterion("postage_template_id <=", value, "postageTemplateId");
            return (Criteria) this;
        }

        public Criteria andPostageTemplateIdIn(List<Long> values) {
            addCriterion("postage_template_id in", values, "postageTemplateId");
            return (Criteria) this;
        }

        public Criteria andPostageTemplateIdNotIn(List<Long> values) {
            addCriterion("postage_template_id not in", values, "postageTemplateId");
            return (Criteria) this;
        }

        public Criteria andPostageTemplateIdBetween(Long value1, Long value2) {
            addCriterion("postage_template_id between", value1, value2, "postageTemplateId");
            return (Criteria) this;
        }

        public Criteria andPostageTemplateIdNotBetween(Long value1, Long value2) {
            addCriterion("postage_template_id not between", value1, value2, "postageTemplateId");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("amount is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("amount is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(Long value) {
            addCriterion("amount =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(Long value) {
            addCriterion("amount <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(Long value) {
            addCriterion("amount >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("amount >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(Long value) {
            addCriterion("amount <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(Long value) {
            addCriterion("amount <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<Long> values) {
            addCriterion("amount in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<Long> values) {
            addCriterion("amount not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(Long value1, Long value2) {
            addCriterion("amount between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(Long value1, Long value2) {
            addCriterion("amount not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andBulkNoIsNull() {
            addCriterion("bulk_no is null");
            return (Criteria) this;
        }

        public Criteria andBulkNoIsNotNull() {
            addCriterion("bulk_no is not null");
            return (Criteria) this;
        }

        public Criteria andBulkNoEqualTo(Long value) {
            addCriterion("bulk_no =", value, "bulkNo");
            return (Criteria) this;
        }

        public Criteria andBulkNoNotEqualTo(Long value) {
            addCriterion("bulk_no <>", value, "bulkNo");
            return (Criteria) this;
        }

        public Criteria andBulkNoGreaterThan(Long value) {
            addCriterion("bulk_no >", value, "bulkNo");
            return (Criteria) this;
        }

        public Criteria andBulkNoGreaterThanOrEqualTo(Long value) {
            addCriterion("bulk_no >=", value, "bulkNo");
            return (Criteria) this;
        }

        public Criteria andBulkNoLessThan(Long value) {
            addCriterion("bulk_no <", value, "bulkNo");
            return (Criteria) this;
        }

        public Criteria andBulkNoLessThanOrEqualTo(Long value) {
            addCriterion("bulk_no <=", value, "bulkNo");
            return (Criteria) this;
        }

        public Criteria andBulkNoIn(List<Long> values) {
            addCriterion("bulk_no in", values, "bulkNo");
            return (Criteria) this;
        }

        public Criteria andBulkNoNotIn(List<Long> values) {
            addCriterion("bulk_no not in", values, "bulkNo");
            return (Criteria) this;
        }

        public Criteria andBulkNoBetween(Long value1, Long value2) {
            addCriterion("bulk_no between", value1, value2, "bulkNo");
            return (Criteria) this;
        }

        public Criteria andBulkNoNotBetween(Long value1, Long value2) {
            addCriterion("bulk_no not between", value1, value2, "bulkNo");
            return (Criteria) this;
        }

        public Criteria andWeightNoIsNull() {
            addCriterion("weight_no is null");
            return (Criteria) this;
        }

        public Criteria andWeightNoIsNotNull() {
            addCriterion("weight_no is not null");
            return (Criteria) this;
        }

        public Criteria andWeightNoEqualTo(Long value) {
            addCriterion("weight_no =", value, "weightNo");
            return (Criteria) this;
        }

        public Criteria andWeightNoNotEqualTo(Long value) {
            addCriterion("weight_no <>", value, "weightNo");
            return (Criteria) this;
        }

        public Criteria andWeightNoGreaterThan(Long value) {
            addCriterion("weight_no >", value, "weightNo");
            return (Criteria) this;
        }

        public Criteria andWeightNoGreaterThanOrEqualTo(Long value) {
            addCriterion("weight_no >=", value, "weightNo");
            return (Criteria) this;
        }

        public Criteria andWeightNoLessThan(Long value) {
            addCriterion("weight_no <", value, "weightNo");
            return (Criteria) this;
        }

        public Criteria andWeightNoLessThanOrEqualTo(Long value) {
            addCriterion("weight_no <=", value, "weightNo");
            return (Criteria) this;
        }

        public Criteria andWeightNoIn(List<Long> values) {
            addCriterion("weight_no in", values, "weightNo");
            return (Criteria) this;
        }

        public Criteria andWeightNoNotIn(List<Long> values) {
            addCriterion("weight_no not in", values, "weightNo");
            return (Criteria) this;
        }

        public Criteria andWeightNoBetween(Long value1, Long value2) {
            addCriterion("weight_no between", value1, value2, "weightNo");
            return (Criteria) this;
        }

        public Criteria andWeightNoNotBetween(Long value1, Long value2) {
            addCriterion("weight_no not between", value1, value2, "weightNo");
            return (Criteria) this;
        }

        public Criteria andRegionIsNull() {
            addCriterion("region is null");
            return (Criteria) this;
        }

        public Criteria andRegionIsNotNull() {
            addCriterion("region is not null");
            return (Criteria) this;
        }

        public Criteria andRegionEqualTo(String value) {
            addCriterion("region =", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotEqualTo(String value) {
            addCriterion("region <>", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionGreaterThan(String value) {
            addCriterion("region >", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionGreaterThanOrEqualTo(String value) {
            addCriterion("region >=", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLessThan(String value) {
            addCriterion("region <", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLessThanOrEqualTo(String value) {
            addCriterion("region <=", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLike(String value) {
            addCriterion("region like", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotLike(String value) {
            addCriterion("region not like", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionIn(List<String> values) {
            addCriterion("region in", values, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotIn(List<String> values) {
            addCriterion("region not in", values, "region");
            return (Criteria) this;
        }

        public Criteria andRegionBetween(String value1, String value2) {
            addCriterion("region between", value1, value2, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotBetween(String value1, String value2) {
            addCriterion("region not between", value1, value2, "region");
            return (Criteria) this;
        }

        public Criteria andCarrayAwayIsNull() {
            addCriterion("carray_away is null");
            return (Criteria) this;
        }

        public Criteria andCarrayAwayIsNotNull() {
            addCriterion("carray_away is not null");
            return (Criteria) this;
        }

        public Criteria andCarrayAwayEqualTo(Byte value) {
            addCriterion("carray_away =", value, "carrayAway");
            return (Criteria) this;
        }

        public Criteria andCarrayAwayNotEqualTo(Byte value) {
            addCriterion("carray_away <>", value, "carrayAway");
            return (Criteria) this;
        }

        public Criteria andCarrayAwayGreaterThan(Byte value) {
            addCriterion("carray_away >", value, "carrayAway");
            return (Criteria) this;
        }

        public Criteria andCarrayAwayGreaterThanOrEqualTo(Byte value) {
            addCriterion("carray_away >=", value, "carrayAway");
            return (Criteria) this;
        }

        public Criteria andCarrayAwayLessThan(Byte value) {
            addCriterion("carray_away <", value, "carrayAway");
            return (Criteria) this;
        }

        public Criteria andCarrayAwayLessThanOrEqualTo(Byte value) {
            addCriterion("carray_away <=", value, "carrayAway");
            return (Criteria) this;
        }

        public Criteria andCarrayAwayIn(List<Byte> values) {
            addCriterion("carray_away in", values, "carrayAway");
            return (Criteria) this;
        }

        public Criteria andCarrayAwayNotIn(List<Byte> values) {
            addCriterion("carray_away not in", values, "carrayAway");
            return (Criteria) this;
        }

        public Criteria andCarrayAwayBetween(Byte value1, Byte value2) {
            addCriterion("carray_away between", value1, value2, "carrayAway");
            return (Criteria) this;
        }

        public Criteria andCarrayAwayNotBetween(Byte value1, Byte value2) {
            addCriterion("carray_away not between", value1, value2, "carrayAway");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table postage_package_condition
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}