package com.hycxkj.postage.bean;

import com.hycxkj.common.annotation.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
/**
 * 实体类对应的数据表为：  postage_postage_template
 * @author 陈少平
 * @date 2018-05-06 18:48:41
 */
@ApiModel(value ="PostageTemplate")
public class PostageTemplate implements Serializable {
    @PrimaryKey
    @ApiModelProperty(value = "")
    private Long id;

    @ApiModelProperty(value = "商家ID")
    private Long busiId;

    @ApiModelProperty(value = "模板名称")
    private String name;

    @ApiModelProperty(value = "商品地址")
    private String addr;

    @ApiModelProperty(value = "是否包邮0：不是，1：是")
    private Boolean packageMail;

    @ApiModelProperty(value = "计价方式(1:按件 2: 按重量 3:按体积)")
    private Byte valuationmodel;

    @ApiModelProperty(value = "是否指定条件包邮(0: 否  1:是)")
    private Boolean isPackageCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table postage_postage_template
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getBusiId() {
        return busiId;
    }

    public void setBusiId(Long busiId) {
        this.busiId = busiId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddr() {
        return addr;
    }

    public void setAddr(String addr) {
        this.addr = addr;
    }

    public Boolean getPackageMail() {
        return packageMail;
    }

    public void setPackageMail(Boolean packageMail) {
        this.packageMail = packageMail;
    }

    public Byte getValuationmodel() {
        return valuationmodel;
    }

    public void setValuationmodel(Byte valuationmodel) {
        this.valuationmodel = valuationmodel;
    }

    public Boolean getIsPackageCondition() {
        return isPackageCondition;
    }

    public void setIsPackageCondition(Boolean isPackageCondition) {
        this.isPackageCondition = isPackageCondition;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", busiId=").append(busiId);
        sb.append(", name=").append(name);
        sb.append(", addr=").append(addr);
        sb.append(", packageMail=").append(packageMail);
        sb.append(", valuationmodel=").append(valuationmodel);
        sb.append(", isPackageCondition=").append(isPackageCondition);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PostageTemplate other = (PostageTemplate) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getBusiId() == null ? other.getBusiId() == null : this.getBusiId().equals(other.getBusiId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getAddr() == null ? other.getAddr() == null : this.getAddr().equals(other.getAddr()))
            && (this.getPackageMail() == null ? other.getPackageMail() == null : this.getPackageMail().equals(other.getPackageMail()))
            && (this.getValuationmodel() == null ? other.getValuationmodel() == null : this.getValuationmodel().equals(other.getValuationmodel()))
            && (this.getIsPackageCondition() == null ? other.getIsPackageCondition() == null : this.getIsPackageCondition().equals(other.getIsPackageCondition()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getBusiId() == null) ? 0 : getBusiId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getAddr() == null) ? 0 : getAddr().hashCode());
        result = prime * result + ((getPackageMail() == null) ? 0 : getPackageMail().hashCode());
        result = prime * result + ((getValuationmodel() == null) ? 0 : getValuationmodel().hashCode());
        result = prime * result + ((getIsPackageCondition() == null) ? 0 : getIsPackageCondition().hashCode());
        return result;
    }
}